#Main playbook for the project
- name: Setup Yolomy E-commerce APP
  hosts: all
  collections:
  - community.docker
  become: yes
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: always

  roles:
    - role: common
      tags: common

    - role: docker
      tags: docker

    - role: mongodb
      tags: mongodb

    - role: backend
      tags: backend

    - role: frontend
      tags: frontend

    - role: deploy
      tags: deploy

  post_tasks:
    - name: Verify application is running
      uri:
        url: "http://localhost:3000"
        status_code: 200
      register: frontend_status
      ignore_errors: yes
      tags: verify
      retries: 3
      delay: 10
      until: frontend_status.status == 200 or frontend_status.status == 302

    - name: Display application status
      debug:
        msg: "Application is running and accessible at http://localhost:3000"
      when: frontend_status.status == 200 or frontend_status.status == 302
      tags: verify
      
    - name: Display application failure
      debug:
        msg: "Application may not be running correctly. Check container logs."
      when: frontend_status.status != 200 and frontend_status.status != 302
      tags: verify
    