apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark-yolo-client
  labels:
    app: mark-yolo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mark-yolo-client
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mark-yolo-client
    spec:
      containers:
      - name: mark-yolo-client
        image: maqacm/mark-yolo-client:v1.0.2
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mark-yolo-client
  labels:
    app: mark-yolo-client
  annotations:
    cloud.google.com/load-balancer-type: "External"
    service.beta.kubernetes.io/gcp-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3000
    protocol: TCP
  selector:
    app: mark-yolo-client
